In [1]:
# Array #NumPy

In [2]:
import numpy as np

arr_a = np.array([3,6,9])

arr_b = arr_a/3 # performing element wise operations

print(arr_b)

[1. 2. 3.]


In [3]:
arr_ones = np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [4]:
multi_arr_ones = np.ones((3,4)) # Creating a 2D array with 3 rows and 4 columns

print (multi_arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Linear Lists # Stacks and Queues

ls = [1,2,3,4,5]

ls.append(6)

print (ls)


[1, 2, 3, 4, 5, 6]


In [6]:
ls.pop()

print(ls)

ls.pop()

print(ls)

[1, 2, 3, 4, 5]
[1, 2, 3, 4]


In [9]:
# Convert this to queue?

ls.pop(0)

print (ls)

[2, 3, 4]


In [16]:
from collections import deque

ls = deque()

ls.append(1)
ls.append(2)
ls.append(3)

print (ls)

print (ls.popleft())

print (ls)

deque([1, 2, 3])
1
deque([2, 3])


In [39]:
from queue import Queue

ls = Queue(maxsize = 7)

print (ls.qsize())

ls.put(1)
ls.put(2)
ls.put(3)
ls.put(4)
ls.put(5)

print (ls.qsize())

print (ls.queue)

ls.get()

print (ls.queue)


0
5
deque([1, 2, 3, 4, 5])
deque([2, 3, 4, 5])
